'use strict';
const db = supabase.createClient('https://hgvvnfzevklbanudjaff.supabase.co','sb_publishable_pxedY3zoVI76h4plROq4ag_m38l4grC');
const $ = s => document.querySelector(s);
let user=null, muted=true, mode='all', videos=[], offset=0, loading=false, exhausted=false, currentComment=null, previewURL=null, feedVersion=0;
const pageSize=12;
function el(tag,cls,text){const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;}
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('show'),4500);}
function checked(result){if(result.error)throw result.error;return result.data;}
function displayName(){return String(user?.user_metadata?.full_name||user?.user_metadata?.name||'Creator').slice(0,80);}
function openDialog(id){document.querySelectorAll('video').forEach(v=>v.pause());$(id).showModal();}
function requireUser(){if(user)return true;openDialog('#login-dialog');return false;}
function resume(){const v=activeVideo();if(v&&!document.querySelector('dialog[open]'))v.play().catch(()=>{});}
for(const d of document.querySelectorAll('dialog')){d.querySelector('.close').onclick=()=>d.close();d.addEventListener('close',resume);d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}});}
function activeVideo(){const slides=[...document.querySelectorAll('.video-slide')];let best=null,distance=Infinity;const top=$('#feed').getBoundingClientRect().top;for(const slide of slides){const d=Math.abs(slide.getBoundingClientRect().top-top);if(d<distance){best=slide;distance=d;}}return best?.querySelector('video');}
const observer=new IntersectionObserver(entries=>{for(const entry of entries){const video=entry.target.querySelector('video');if(entry.isIntersecting){video.muted=muted;if(!document.hidden&&!document.querySelector('dialog[open]'))video.play().catch(()=>{});if(Number(entry.target.dataset.index)>=videos.length-3)loadFeed();}else video.pause();}},{root:$('#feed'),threshold:.7});
async function refresh(){feedVersion++;observer.disconnect();$('#feed').replaceChildren();videos=[];offset=0;exhausted=false;loading=false;await loadFeed();}
function emptyState(title,description,retry=false){const box=el('div','empty');box.append(el('span','empty-mark','◒'),el('h2','',title),el('p','',description));const btn=el('button','primary',retry?'Try again':'Upload the first video');btn.onclick=retry?refresh:showUpload;box.append(btn);if(!retry){const preview=el('button','secondary','Or preview a video from your device');preview.onclick=localPreview;box.append(preview);}$('#feed').replaceChildren(box);}
async function loadFeed(){if(loading||exhausted)return;loading=true;const version=feedVersion;try{let query=db.from('loop_videos').select('*').order('created_at',{ascending:false}).order('id',{ascending:false}).range(offset,offset+pageSize-1);if(mode==='mine')query=query.eq('user_id',user.id);const rows=checked(await query);if(version!==feedVersion)return;exhausted=rows.length<pageSize;offset+=rows.length;if(!rows.length&&!videos.length){emptyState(mode==='mine'?'Your story starts here.':'Be the first moment.','Upload a video, add a title, and give everyone something to scroll for.');return;}for(const row of rows){const index=videos.length;videos.push(row);const slide=buildSlide(row,index);$('#feed').append(slide);observer.observe(slide);}}catch(e){if(version===feedVersion){if(!videos.length)emptyState('Couldn’t load the feed.',e.message,true);else toast(e.message);}}finally{if(version===feedVersion)loading=false;}}
function buildSlide(row,index){const slide=el('article','video-slide');slide.dataset.index=index;const wrap=el('div','video-wrap');const video=el('video');video.src=row.localURL||db.storage.from('loop-videos').getPublicUrl(row.storage_path).data.publicUrl;video.loop=true;video.playsInline=true;video.muted=muted;video.preload='metadata';video.setAttribute('aria-label',row.title);wrap.append(video);
const controls=el('div','video-controls'),play=el('button','glass','▶'),sound=el('button','glass',muted?'♪̸':'♪');play.setAttribute('aria-label','Play video');sound.setAttribute('aria-label',muted?'Unmute video':'Mute video');controls.append(play,sound);wrap.append(controls);const toggle=()=>video.paused?video.play().catch(()=>toast('This video cannot be played in your browser.')):video.pause();video.onclick=toggle;play.onclick=toggle;video.onplay=()=>{play.textContent='Ⅱ';play.setAttribute('aria-label','Pause video');};video.onpause=()=>{play.textContent='▶';play.setAttribute('aria-label','Play video');};video.onerror=()=>{const msg=el('p','play-error','Video unavailable or unsupported. Try MP4 (H.264).');wrap.append(msg);};sound.onclick=()=>{muted=!muted;document.querySelectorAll('.video-wrap video').forEach(v=>v.muted=muted);document.querySelectorAll('[data-sound]').forEach(b=>{b.textContent=muted?'♪̸':'♪';b.setAttribute('aria-label',muted?'Unmute video':'Mute video');});};sound.dataset.sound='true';
const caption=el('div','video-caption'),creator=el('div','creator');creator.append(el('span','avatar',(row.creator||'C')[0].toUpperCase()),el('span','',row.creator));caption.append(creator,el('h2','',row.title),el('small','',row.localURL?'Private device preview · not published':'Original video · '+new Date(row.created_at).toLocaleDateString(undefined,{month:'short',day:'numeric'})));wrap.append(caption);const seek=el('input','seek');seek.type='range';seek.min='0';seek.max='100';seek.value='0';seek.step='.1';seek.setAttribute('aria-label','Video progress');video.ontimeupdate=()=>{if(Number.isFinite(video.duration))seek.value=String(video.currentTime/video.duration*100);};seek.oninput=()=>{if(Number.isFinite(video.duration))video.currentTime=Number(seek.value)/100*video.duration;};wrap.append(seek);slide.append(wrap);
const actions=el('div','actions');function action(symbol,label){const b=el('button','action');b.append(el('span','circle',symbol),el('span','',label));b.setAttribute('aria-label',label);actions.append(b);return b;}const like=action('♥','Like'),comment=action('☏','Comment');like.setAttribute('aria-pressed','false');like.onclick=async()=>{if(row.localURL)return toast('Publish your video to enable likes.');if(!requireUser())return;like.disabled=true;try{const isLiked=like.getAttribute('aria-pressed')==='true';checked(await(isLiked?db.from('loop_likes').delete().eq('video_id',row.id).eq('user_id',user.id):db.from('loop_likes').insert({video_id:row.id,user_id:user.id})));await counts();}catch(e){toast(e.message);}finally{like.disabled=false;}};comment.onclick=()=>{if(row.localURL)return toast('Publish your video to start the conversation.');showComments(row);};if(user&&row.user_id===user.id){const remove=action('×','Delete');remove.onclick=async()=>{if(!confirm('Delete this video and its comments?'))return;try{checked(await db.from('loop_videos').delete().eq('id',row.id).eq('user_id',user.id));const result=await db.storage.from('loop-videos').remove([row.storage_path]);if(result.error)toast('Video removed. Storage cleanup failed: '+result.error.message);else toast('Video deleted.');await refresh();}catch(e){toast(e.message);}};}slide.append(actions);
async function counts(){const [likes,comments,own]=await Promise.all([db.from('loop_likes').select('*',{count:'exact',head:true}).eq('video_id',row.id),db.from('loop_comments').select('*',{count:'exact',head:true}).eq('video_id',row.id),user?db.from('loop_likes').select('video_id').eq('video_id',row.id).eq('user_id',user.id):Promise.resolve({data:[]})]);checked(likes);checked(comments);checked(own);like.lastChild.textContent=String(likes.count||0);comment.lastChild.textContent=String(comments.count||0);like.setAttribute('aria-pressed',String(!!own.data?.length));}if(!row.localURL)counts().catch(()=>{});row.updateCounts=counts;return slide;}
async function localPreview(){const input=el('input');input.type='file';input.accept='video/*';input.onchange=()=>{const file=input.files[0];if(!file)return;observer.disconnect();$('#feed').replaceChildren();videos=[{localURL:URL.createObjectURL(file),title:file.name,creator:'You'}];exhausted=true;const slide=buildSlide(videos[0],0);$('#feed').append(slide);observer.observe(slide);};input.click();}
function showUpload(){if(requireUser())openDialog('#upload-dialog');}document.querySelectorAll('.upload-trigger').forEach(b=>b.onclick=showUpload);
$('#home').onclick=()=>{mode='all';$('#home').classList.add('active');$('#mine').classList.remove('active');$('#feed-label').textContent='For you';$('#feed-title').textContent='A little discovery.';refresh();};$('#mine').onclick=()=>{if(!requireUser())return;mode='mine';$('#mine').classList.add('active');$('#home').classList.remove('active');$('#feed-label').textContent='My videos';$('#feed-title').textContent='Your moments.';refresh();};
$('#mobile-mine').onclick=()=>{if(mode==='mine')$('#home').click();else $('#mine').click();$('#mobile-mine').textContent=mode==='mine'?'For you':'My videos';};
document.querySelectorAll('.auth-button').forEach(b=>b.onclick=async()=>{if(user){try{checked(await db.auth.signOut());toast('Signed out.');}catch(e){toast(e.message);}}else openDialog('#login-dialog');});
$('#google-login').onclick=async()=>{const btn=$('#google-login');btn.disabled=true;$('#login-error').textContent='';try{const settings=await fetch('https://hgvvnfzevklbanudjaff.supabase.co/auth/v1/settings',{headers:{apikey:'sb_publishable_pxedY3zoVI76h4plROq4ag_m38l4grC'}}).then(r=>r.json());if(!settings.external?.google)throw new Error('Google sign-in is not available yet. The site owner needs to enable Google in Supabase Authentication.');checked(await db.auth.signInWithOAuth({provider:'google',options:{redirectTo:location.origin+location.pathname}}));}catch(e){$('#login-error').textContent=e.message;}finally{btn.disabled=false;}};
function selectFile(file){if(!file)return;if(!['video/mp4','video/webm','video/quicktime'].includes(file.type)||file.size>52428800){$('#video-file').value='';toast('Choose an MP4, WebM or MOV video under 50 MB.');return;}$('#file-name').textContent=file.name;if(previewURL)URL.revokeObjectURL(previewURL);previewURL=URL.createObjectURL(file);$('#upload-preview').src=previewURL;$('#upload-preview').hidden=false;}
$('#video-file').onchange=e=>selectFile(e.target.files[0]);const drop=$('#drop-zone');for(const name of ['dragover','dragleave','drop'])drop.addEventListener(name,e=>{e.preventDefault();drop.classList.toggle('drag',name==='dragover');if(name==='drop'&&e.dataTransfer.files.length){$('#video-file').files=e.dataTransfer.files;selectFile(e.dataTransfer.files[0]);}});$('#video-title').oninput=e=>$('#title-count').textContent=e.target.value.length+' / 160';
$('#upload-form').onsubmit=async e=>{e.preventDefault();if(!requireUser())return;const file=$('#video-file').files[0],title=$('#video-title').value.trim();if(!file||!title)return toast('Choose a video and add a title.');if(file.size>52428800||!['video/mp4','video/webm','video/quicktime'].includes(file.type))return toast('Choose a supported video under 50 MB.');const btn=$('#publish');btn.disabled=true;const owner=user.id,path=owner+'/'+crypto.randomUUID()+({ 'video/mp4':'.mp4','video/webm':'.webm','video/quicktime':'.mov'}[file.type]);let uploaded=false,published=false;$('#upload-status').textContent='Uploading your video… Keep this window open.';try{checked(await db.storage.from('loop-videos').upload(path,file,{contentType:file.type,upsert:false}));uploaded=true;checked(await db.from('loop_videos').insert({user_id:owner,creator:displayName(),title,storage_path:path}));published=true;$('#upload-dialog').close();$('#upload-form').reset();$('#upload-preview').pause();$('#upload-preview').hidden=true;$('#upload-preview').removeAttribute('src');if(previewURL)URL.revokeObjectURL(previewURL);$('#file-name').textContent='Choose a video or drop it here';$('#title-count').textContent='0 / 160';$('#upload-status').textContent='';toast('Your moment is live.');await refresh();}catch(e){if(uploaded&&!published)await db.storage.from('loop-videos').remove([path]);$('#upload-status').textContent='Upload failed: '+e.message;}finally{btn.disabled=false;}};
async function showComments(row){currentComment=row;$('#comment-text').value='';$('#comment-error').textContent='';openDialog('#comments-dialog');await loadComments();}
async function loadComments(){const row=currentComment;$('#comment-list').textContent='Loading comments…';try{const response=await db.from('loop_comments').select('*',{count:'exact'}).eq('video_id',row.id).order('created_at',{ascending:false}).limit(100);const rows=checked(response);if(currentComment!==row)return;$('#comment-total').textContent=String(response.count||0);$('#comment-list').replaceChildren();if(!rows.length)$('#comment-list').append(el('p','','No comments yet. Start the conversation.'));for(const c of rows){const item=el('div','comment');item.append(el('strong','',c.creator),el('p','',c.body),el('small','',new Date(c.created_at).toLocaleDateString()));if(user?.id===c.user_id){const remove=el('button','','Delete');remove.onclick=async()=>{try{checked(await db.from('loop_comments').delete().eq('id',c.id).eq('user_id',user.id));await loadComments();row.updateCounts?.().catch(()=>{});}catch(e){$('#comment-error').textContent=e.message;}};item.append(remove);}$('#comment-list').append(item);}if(response.count>100)$('#comment-list').append(el('p','small','Showing the newest 100 comments.'));}catch(e){$('#comment-list').textContent='Couldn’t load comments.';$('#comment-error').textContent=e.message;}}
$('#comment-form').onsubmit=async e=>{e.preventDefault();if(!user){$('#comments-dialog').close();requireUser();return;}const body=$('#comment-text').value.trim();if(!body)return;const btn=e.target.querySelector('button');btn.disabled=true;try{checked(await db.from('loop_comments').insert({video_id:currentComment.id,user_id:user.id,creator:displayName(),body}));$('#comment-text').value='';await loadComments();currentComment.updateCounts?.().catch(()=>{});}catch(e){$('#comment-error').textContent=e.message;}finally{btn.disabled=false;}};
$('#feed').addEventListener('scroll',()=>{if($('#feed').scrollTop+$('#feed').clientHeight>=$('#feed').scrollHeight-100)loadFeed();},{passive:true});
document.addEventListener('keydown',e=>{if(document.querySelector('dialog[open]')||/INPUT|TEXTAREA/.test(e.target.tagName))return;if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();$('#feed').scrollBy({top:$('#feed').clientHeight*(e.key==='ArrowDown'?1:-1),behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});}if(e.code==='Space'){e.preventDefault();const v=activeVideo();if(v)v.paused?v.play().catch(()=>{}):v.pause();}});document.addEventListener('visibilitychange',()=>document.hidden?document.querySelectorAll('video').forEach(v=>v.pause()):resume());
let initialized=false;db.auth.onAuthStateChange((_event,session)=>{const changed=user?.id!==session?.user?.id;user=session?.user||null;$('#account').textContent=user?displayName():'';document.querySelectorAll('.auth-button').forEach(b=>b.textContent=user?'Sign out':b.classList.contains('compact')?'Sign in':'Sign in with Google');if(changed&&initialized){if(!user){mode='all';$('#feed-label').textContent='For you';$('#feed-title').textContent='A little discovery.';$('#home').classList.add('active');$('#mine').classList.remove('active');$('#mobile-mine').textContent='My videos';}setTimeout(refresh,0);}});
(async()=>{try{const {data,error}=await db.auth.getSession();if(error)throw error;user=data.session?.user||null;}catch(e){toast(e.message);}initialized=true;await refresh();})();
